import React, {useState, useEffect} from 'react'
import { collection, getDocs } from 'firebase/firestore'
import { db } from '../firebase-config'
import { CircularIndeterminate } from '../loadinganimation'
import DisplayPost from './DisplayPost'

const Home = () => {
  const [allPosts, setAllPosts] = useState([])
  const [loading, setLoading] = useState(true)
  const [search, setSearch] = useState(null)
  const [searchResult, setSearchResult] = useState([])

  const postRef = collection(db, "posts")

  useEffect(() => { 
    if(allPosts && search) {
      setSearchResult(allPosts.filter((item) => item.user.toLowerCase().includes(search) || item.prompt.toLowerCase().includes(search)))
    }
  }, [search])

  useEffect(() => {
    setLoading(true)
    const getPosts = async () => {
      await getDocs(postRef)
      .then(data => {setAllPosts(data.docs.map(doc => ({...doc.data(), id: doc.id})));
      setLoading(false)
    })
    }
    getPosts() 
  }, [])

  return (
    <div className='container mt-2 style={{marginTop: "40px"}}'>
      <section className='max-w-7xl max-30px-auto'>
    <h1 className="font-extrabold text-[#222328] text-[40px]">The Community <span>Showcase!</span></h1>
    <p className="mt-2 text-[#666e75] text-[15px] max-w-[500px]">Browse through a collection of imaginative and visually stunning images generated by DALL-E AI</p>

    <div className='generate-form mt-16'>
      <input 
      type='text' 
      name='search' 
      placeholder='search your prompt...' 
      onChange={e=>setSearch(e.target.value)}
      value={search}
      />
    </div>

    <div className="m-10">
      {loading? (
        <div className="flex justify-center item-center">
          <CircularIndeterminate/>
        </div>
      ): (
        <div className='grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3'>
       
        {search && searchResult ? searchResult.map(post => <DisplayPost post = {post} />)
        :
        allPosts && allPosts.map(post => (
          <DisplayPost post={post}/>
        ))}
        </div>
      )}
    </div>
    </section>
  </div>
  )
}

export default Home